use_frameworks!
platform :ios, '9.0'

target 'CHComponent_Example' do
  pod 'CHComponent', :path => '../'

  target 'CHComponent_Tests' do
    inherit! :search_paths

    pod 'FBSnapshotTestCase' , '~> 2.1.4'
  end
end
